/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2020-11-09 04:58:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.*;
import java.util.*;
import util.Info;
import dao.*;
import java.util.*;
import util.Info;
import dao.*;
import java.util.*;
import util.Info;

public final class goupiao_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/head.jsp", Long.valueOf(1603278522000L));
    _jspx_dependants.put("/foot.jsp", Long.valueOf(1603603727214L));
    _jspx_dependants.put("/WEB-INF/sql.tld", Long.valueOf(1603278522000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1603278522000L));
    _jspx_dependants.put("jar:file:/D:/Users/peixu/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/QuNaWang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("dao");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("util.Info");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>去哪了网机票网站</title>\r\n");
      out.write("    <meta name=\"force-rendering\" contect=\"WebKit\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\">\r\n");
      out.write("    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"chrome=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"qtstyle/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"qtstyle/bootstrap/css/bootstrap-theme.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"qtstyle/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\r\n");
      out.write("    <script language=\"javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery.validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div style=\"padding: 10px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\"><!-- 当你点击购买机票时，就会跳转到这个界面 -->\r\n");
      out.write("        <div class=\"panel panel-default\">\r\n");
      out.write("            <div class=\"panel-heading\">\r\n");
      out.write("                添加购票:\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"panel-body\">\r\n");
      out.write("                <form action=\"goupiaoinsert.do\" method=\"post\" name=\"form1\" id=\"form1\"><!-- form 标签开始 -->\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">票务编号</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.piaowubianhao}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"piaowubianhao\" name=\"piaowubianhao\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.piaowubianhao)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">航班名称</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.hangbanmingcheng}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"hangbanmingcheng\"\r\n");
      out.write("                                                                  name=\"hangbanmingcheng\"\r\n");
      out.write("                                                                  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.hangbanmingcheng)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">出发地</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.chufadi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"chufadi\" name=\"chufadi\"\r\n");
      out.write("                                                         value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.chufadi)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">目的地</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.mudidi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"mudidi\" name=\"mudidi\"\r\n");
      out.write("                                                        value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.mudidi)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">起飞时间</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.qifeishijian}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"qifeishijian\" name=\"qifeishijian\"\r\n");
      out.write("                                                              value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.qifeishijian)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">票价</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.piaojia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"piaojia\" name=\"piaojia\"\r\n");
      out.write("                                                         value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.piaojia)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">登机口</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${readMap.dengjikou}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"dengjikou\" name=\"dengjikou\"\r\n");
      out.write("                                                           value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Info.html(readMap.dengjikou)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">购票人姓名<span\r\n");
      out.write("                                    style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" style=\"width:150px;\" data-rule-required=\"true\"\r\n");
      out.write("                                       data-msg-required=\"请填写购票人姓名\" id=\"goupiaorenxingming\" name=\"goupiaorenxingming\"\r\n");
      out.write("                                       value=\"\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">手机<span\r\n");
      out.write("                                    style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" style=\"width:150px;\" data-rule-required=\"true\"\r\n");
      out.write("                                       data-msg-required=\"请填写手机\" phone=\"true\" data-msg-phone=\"请输入正确手机号码\" id=\"shouji\"\r\n");
      out.write("                                       name=\"shouji\" value=\"\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">身份证号<span\r\n");
      out.write("                                    style=\"color: red;\">*</span></label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" style=\"width:150px;\" data-rule-required=\"true\"\r\n");
      out.write("                                       data-msg-required=\"请填写身份证号\" idcard=\"true\" data-msg-email=\"请输入有效身份证号码\"\r\n");
      out.write("                                       id=\"shenfenzhenghao\" name=\"shenfenzhenghao\" value=\"\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\">购票人</label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" style=\"width:150px;\" readonly=\"readonly\"\r\n");
      out.write("                                       id=\"goupiaoren\" name=\"goupiaoren\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <label style=\"width: 120px;min-height:18px;text-align: right\" class=\"col-sm-2\"> </label>\r\n");
      out.write("                            <div class=\"col-sm-8\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"jipiaoid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/><input name=\"referer\"\r\n");
      out.write("                                                                                                 value=\"");
      out.print(request.getHeader("referer"));
      out.write("\"\r\n");
      out.write("                                                                                                 type=\"hidden\"/><input\r\n");
      out.write("                                    type=\"hidden\" name=\"iszf\" value=\"否\"/>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\" name=\"Submit\">\r\n");
      out.write("                                    提交\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button type=\"reset\" class=\"btn btn-default\" name=\"Submit2\">\r\n");
      out.write("                                    重置\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div><!--form标签结束--></form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- container定宽，并剧中结束 --></div>\r\n");
      out.write("        \r\n");
      out.write("    <script>\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $('#form1').validate();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"qtstyle/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
