/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2020-11-09 04:58:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.zhifu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import util.Info;
import dao.CommDAO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.CommDAO");
    _jspx_imports_classes.add("util.Info");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML XMLNS:CC>\r\n");
      out.write("<HEAD><TITLE>支付宝 - 网上支付 安全快速！</TITLE>\r\n");
      out.write("    <META http-equiv=Content-Type content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <META content=网上购物/网上支付/安全支付/安全购物/购物，安全/支付,安全/支付宝/安全,支付/安全，购物/支付,\r\n");
      out.write("          name=description 在线 付款,收款 网上,贸易 网上贸易.>\r\n");
      out.write("    <META content=网上购物/网上支付/安全支付/安全购物/购物，安全/支付,安全/支付宝/安全,支付/安全，购物/支付, name=keywords\r\n");
      out.write("          在线 付款,收款 网上,贸易 网上贸易.>\r\n");
      out.write("    <LINK href=\"images/layout.css\"\r\n");
      out.write("          type=text/css rel=stylesheet>\r\n");
      out.write("\r\n");
      out.write("    <SCRIPT language=JavaScript>\r\n");
      out.write("        <!--\r\n");
      out.write("        //校验输入框  -->\r\n");
      out.write("        function CheckForm() {\r\n");
      out.write("            if (document.alipayment.aliorder.value.length == 0) {\r\n");
      out.write("                alert(\"请输入图书名称.\");\r\n");
      out.write("                document.alipayment.aliorder.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if (document.alipayment.alimoney.value.length == 0) {\r\n");
      out.write("                alert(\"请输入付款金额.\");\r\n");
      out.write("                document.alipayment.alimoney.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            var reg = new RegExp(/^\\d*\\.?\\d{0,2}$/);\r\n");
      out.write("            if (!reg.test(document.alipayment.alimoney.value)) {\r\n");
      out.write("                alert(\"请正确输入付款金额\");\r\n");
      out.write("                document.alipayment.alimoney.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if (Number(document.alipayment.alimoney.value) < 0.01) {\r\n");
      out.write("                alert(\"付款金额金额最小是0.01.\");\r\n");
      out.write("                document.alipayment.alimoney.focus();\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function glowit(which) {\r\n");
      out.write("            if (document.all.glowtext[which].filters[0].strength == 2)\r\n");
      out.write("                document.all.glowtext[which].filters[0].strength = 1\r\n");
      out.write("            else\r\n");
      out.write("                document.all.glowtext[which].filters[0].strength = 2\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function glowit2(which) {\r\n");
      out.write("            if (document.all.glowtext.filters[0].strength == 2)\r\n");
      out.write("                document.all.glowtext.filters[0].strength = 1\r\n");
      out.write("            else\r\n");
      out.write("                document.all.glowtext.filters[0].strength = 2\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function startglowing() {\r\n");
      out.write("            if (document.all.glowtext && glowtext.length) {\r\n");
      out.write("                for (i = 0; i < glowtext.length; i++)\r\n");
      out.write("                    eval('setInterval(\"glowit(' + i + ')\",150)')\r\n");
      out.write("            } else if (glowtext)\r\n");
      out.write("                setInterval(\"glowit2(0)\", 150)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (document.all)\r\n");
      out.write("            window.onload = startglowing\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </SCRIPT>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<style>\r\n");
      out.write("    <!--\r\n");
      out.write("    #glowtext {\r\n");
      out.write("        filter: glow(color=red, strength=2);\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    -->\r\n");
      out.write("</style>\r\n");
      out.write("<BODY text=#000000 bgColor=#ffffff leftMargin=0 topMargin=4>\r\n");
      out.write("<CENTER>\r\n");
      out.write("\r\n");
      out.write("    <TABLE cellSpacing=0 cellPadding=0 width=760 border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("            <TD class=title>支付宝即时到帐付款快速通道</TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("    <BR>\r\n");
      out.write("    <FORM name=alipayment onSubmit=\"return CheckForm();\" action=alipayto.asp\r\n");
      out.write("          method=post target=\"_blank\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <TABLE cellSpacing=0 cellPadding=0 width=740 border=0>\r\n");
      out.write("                        <TR>\r\n");
      out.write("                            <TD class=form-left>收款方：</TD>\r\n");
      out.write("                            <TD class=form-star>*</TD>\r\n");
      out.write("                            <TD class=form-right>xxxx&nbsp;</TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR>\r\n");
      out.write("                            <TD colspan=\"3\" align=\"center\">\r\n");
      out.write("                                <HR width=600 SIZE=2 color=\"#999999\">\r\n");
      out.write("                            </TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR style=\"display:none\">\r\n");
      out.write("                            <TD class=form-left>订单号：</TD>\r\n");
      out.write("                            <TD class=form-star>*</TD>\r\n");
      out.write("                            <TD class=form-right><INPUT size=30 name=aliorder maxlength=\"200\"\r\n");
      out.write("                                                        value=\"\"><span>如：7月5日定货款。</span></TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR style=\"display:none\">\r\n");
      out.write("                            <TD class=form-left>付款金额：</TD>\r\n");
      out.write("                            <TD class=form-star>*</TD>\r\n");
      out.write("                            <TD class=form-right><INPUT maxLength=10 size=30 name=alimoney\r\n");
      out.write("                                                        onFocus=\"if(Number(this.value)==0){this.value='';}\" value=\"\"\r\n");
      out.write("                                                        readonly=\"readonly\"/>\r\n");
      out.write("                                <span>如：112.21</span></TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR style=\"display:none\">\r\n");
      out.write("                            <TD class=form-left>备注：</TD>\r\n");
      out.write("                            <TD class=form-star></TD>\r\n");
      out.write("                            <TD class=form-right><TEXTAREA name=alibody rows=5 cols=40 wrap=\"physical\"></TEXTAREA><BR>\r\n");
      out.write("                                （如联系方法，图书要求、数量等。100汉字内）\r\n");
      out.write("                            </TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR>\r\n");
      out.write("                            <TD class=form-left>支付方式：</TD>\r\n");
      out.write("                            <TD class=form-star></TD>\r\n");
      out.write("                            <TD class=form-right>\r\n");
      out.write("                                <table>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"directPay\" checked><img\r\n");
      out.write("                                                src=\"images/alipay_1.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"ICBCB2C\"/><img\r\n");
      out.write("                                                src=\"images/ICBC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CMB\"/><img\r\n");
      out.write("                                                src=\"images/CMB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CCB\"/><img\r\n");
      out.write("                                                src=\"images/CCB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"BOCB2C\"><img\r\n");
      out.write("                                                src=\"images/BOC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"ABC\"/><img\r\n");
      out.write("                                                src=\"images/ABC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"COMM\"/><img\r\n");
      out.write("                                                src=\"images/COMM_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"SPDB\"/><img\r\n");
      out.write("                                                src=\"images/SPDB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"GDB\"><img\r\n");
      out.write("                                                src=\"images/GDB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CITIC\"/><img\r\n");
      out.write("                                                src=\"images/CITIC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CEBBANK\"/><img\r\n");
      out.write("                                                src=\"images/CEB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CIB\"/><img\r\n");
      out.write("                                                src=\"images/CIB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"SDB\"><img\r\n");
      out.write("                                                src=\"images/SDB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CMBC\"/><img\r\n");
      out.write("                                                src=\"images/CMBC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"HZCBB2C\"/><img\r\n");
      out.write("                                                src=\"images/HZCB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"SHBANK\"/><img\r\n");
      out.write("                                                src=\"images/SHBANK_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"NBBANK \"><img\r\n");
      out.write("                                                src=\"images/NBBANK_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"SPABANK\"/><img\r\n");
      out.write("                                                src=\"images/SPABANK_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"BJRCB\"/><img\r\n");
      out.write("                                                src=\"images/BJRCB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"ICBCBTB\"/><img\r\n");
      out.write("                                                src=\"images/ENV_ICBC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"CCBBTB\"/><img\r\n");
      out.write("                                                src=\"images/ENV_CCB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"SPDBB2B\"/><img\r\n");
      out.write("                                                src=\"images/ENV_SPDB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"ABCBTB\"/><img\r\n");
      out.write("                                                src=\"images/ENV_ABC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"fdb101\"/><img\r\n");
      out.write("                                                src=\"images/FDB_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                        <td><input type=\"radio\" name=\"pay_bank\" value=\"PSBC-DEBIT\"/><img\r\n");
      out.write("                                                src=\"images/PSBC_OUT.gif\" border=\"0\"/></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                        <TR>\r\n");
      out.write("                            <TD class=form-left></TD>\r\n");
      out.write("                            <TD class=form-star></TD>\r\n");
      out.write("                            <TD class=form-right>\r\n");
      out.write("                                <img src=\"images/button_sure.gif\"\r\n");
      out.write("                                                      onClick=\"javascript:location.href='../zhifu.jsp?id=");
      out.print(request.getParameter("id"));
      out.write("&biao=");
      out.print(request.getParameter("biao"));
      out.write("&referer='+encodeURIComponent(document.referrer);\">\r\n");
      out.write("                            </TD>\r\n");
      out.write("                        </TR>\r\n");
      out.write("                    </TABLE>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td vAlign=top width=205 style=\"font-size:12px;font-family:'宋体'\">\r\n");
      out.write("                    <span id=\"glowtext\">小贴士：</span>\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                        <P class=STYLE1>本通道为<a href=\"http://www.jingmeiru.net\" target=\"_blank\"><strong>高考英语口语考试报名系统收款帐号：xxxx</strong></a>客户专用，采用支付宝付款。请在支付前与本网站达成一致。\r\n");
      out.write("                        </P>\r\n");
      out.write("                        <P class=\"style2\">请务必与<a href=\"http://www.jingmeiru.net\" target=\"_blank\"><strong>高考英语口语考试报名系统收款帐号：xxxx</strong></a>确认好订单和货款后，再付款。可以在快速付款通道里的“标题”、“订单金额”、“付款方”和备注中填入相应的订单信息。\r\n");
      out.write("                        </P>\r\n");
      out.write("                        <P class=\"style2 style3\">&nbsp;</P>\r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("    </FORM>\r\n");
      out.write("\r\n");
      out.write("    <TABLE cellSpacing=1 width=760 border=0>\r\n");
      out.write("        <TR>\r\n");
      out.write("            <TD><FONT class=note-help>如果您点击“购买”按钮，即表示您已经接受“支付宝服务协议”，同意向卖家购买此物品。\r\n");
      out.write("                <BR>\r\n");
      out.write("                您有责任查阅完整的物品登录资料，包括卖家的说明和接受的付款方式。卖家必须承担物品信息正确登录的责任！\r\n");
      out.write("            </FONT>\r\n");
      out.write("            </TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("\r\n");
      out.write("    <TABLE cellSpacing=0 cellPadding=0 width=760 align=center border=0>\r\n");
      out.write("        <TR align=middle>\r\n");
      out.write("            <TD class=\"txt12 lh15\"><A href=\"http://china.alibaba.com/\"\r\n");
      out.write("                                      target=_blank>阿里巴巴旗下公司</A> | 支付宝版权所有 2004-2012\r\n");
      out.write("            </TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        <TR align=middle>\r\n");
      out.write("            <TD class=\"txt12 lh15\"><IMG alt=\"支付宝通过“国际权威安全认证” \"\r\n");
      out.write("                                        src=\"images/logo_vbvv.gif\" border=0><BR>支付宝通过“国际权威安全\r\n");
      out.write("                认证”\r\n");
      out.write("            </TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
